CREATE TABLE question
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    quiz_id INTEGER
);

CREATE TABLE answer
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    question_id INTEGER
);

CREATE TABLE question_answer
(
    question_id INTEGER,
    answer_id INTEGER
);

CREATE TABLE quiz
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortcut VARCHAR,
    secret VARCHAR,
    creator_id INTEGER
);

CREATE TABLE creator
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Put every varchar size &  add constraints by your own