CREATE TABLE question
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    correct_answer_id INTEGER,
    quiz_id INTEGER
);

CREATE TABLE answer
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    question_id INTEGER
);

CREATE TABLE quiz
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret_id VARCHAR,
    shortcut VARCHAR,
    creator_id INTEGER
);

CREATE TABLE secret
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR
);

CREATE TABLE creator
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

-- Put every varchar size &  add constraints by your own