CREATE TABLE question
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    quiz_id INTEGER
);

CREATE TABLE answer
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    question_id INTEGER
);

CREATE TABLE question_answer
(
    question_id INTEGER,
    answer_id INTEGER
);

CREATE TABLE quiz
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortcut VARCHAR,
    secret VARCHAR,
    creator INTEGER
);

CREATE TABLE quiz_user
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    password_hash VARCHAR
);

CREATE TABLE user_token
(
    token VARCHAR PRIMARY KEY,
    user_id INTEGER
);

CREATE TABLE shortcut
(
    shortcut VARCHAR PRIMARY KEY
);

-- Put every varchar size &  add constraints by your own